# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S1u8VOu-6zbU9vppAzZO3Y5pB5uWEZlO
"""

import streamlit as st
import openai
import pandas as pd
import json
import os
from openai import OpenAI


# 🔐 Вставь свой API-ключ OpenAI
#openai.api_key = "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"
client = OpenAI(api_key="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")
# 📥 Загрузка базы знаний
@st.cache_data
def load_kb():
    return pd.read_csv("knowledge_base.csv")

# 🔎 Поиск в базе знаний
def find_in_kb(query, kb):
    for _, row in kb.iterrows():
        if row["запрос"].lower() in query.lower():
            return f"🔍 Найдено решение:\n\n**{row['решение']}**\n\n🔗 [Ссылка]({row['ссылка']})"
    return None

# 📖 Загрузка системного prompt-а
def get_system_prompt():
    with open("system_prompt.txt", encoding="utf-8") as f:
        return f.read()

# 📋 Лог нестандартных запросов
def log_unrecognized(query):
    os.makedirs("logs", exist_ok=True)
    log_path = "logs/unrecognized.json"
    if os.path.exists(log_path):
        with open(log_path, encoding="utf-8") as f:
            logs = json.load(f)
    else:
        logs = []

    logs.append({"запрос": query})
    with open(log_path, "w", encoding="utf-8") as f:
        json.dump(logs, f, ensure_ascii=False, indent=2)



def ask_gpt(query):
    system_prompt = get_system_prompt()
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": query}
    ]

    response = client.chat.completions.create(
        model="gpt-4",
        messages=messages,
        temperature=0.3,
        max_tokens=600
    )

    return response.choices[0].message.content

# 🖥 Интерфейс
st.set_page_config(page_title="ГСП Центр — Помощник", page_icon="💬")
st.title("💬 Интеллектуальный помощник ГСП Центра")

query = st.text_input("Введите ваш вопрос:")

if st.button("Отправить") and query.strip():
    kb = load_kb()
    result = find_in_kb(query, kb)

    if result:
        st.success(result)
    else:
        answer = ask_gpt(query)
        st.info(answer)

        if "не могу" in answer.lower() or "непонятно" in answer.lower():
            log_unrecognized(query)
            st.warning("Запрос не распознан. Он будет передан администратору.")
